export default [
        {   
            "id": 1,
            "link": "TnT-RCD-20A",
            "name": "TnT RCD 20A",
            "productcode": "RENT-TNT-RCDX",
            "category": "PAT Testers",
            "descriptionS" : "Portable Appliance Tester",
            "descriptionL" : "The TnT RCD 20A is Wavecom's most affordable battery powered offering from their latest generation of appliance testers. Offering a wide range of tests, a long lasting Lithium Ion Battery and an integrated Isolation Transformer for RCD Testing, the TnT RCD 20A offers amazing value. With Wavecom's renowned one button testing and easy to read results screen, the TnT RCD 20A will make your PAT testing a breeze.",
            "imageurl" : "tntrcd20a.png",
            "dailyprice": "100",
            "weeklyprice": "300",
            "fortnightlyprice":"480",
            "monthlyprice":"720",
            "rrp":"1098",
            "wavecomlink":"https://www.wavecom.com.au/product_view.php?id_product=1102",
            "features" : [
                "Fully AS/NZS 3760:2022 compliant",
                "Class I, Class II, RCD, Leakage, Extension Lead tests",
                "High power Lithium Ion Battery - Conduct over 3000 sets of Tests on a single charge",
                "Built In Isolation Transformer circuitry for portable RCD Testing",
                "Simplified one button test procedures & easy to read results",
                "20 amp load current capacity - test 10A & 20A appliances",
                "Current calibration certification to Australian standards",
                "Australian made & designed"
            ],
            "usermanual" : "https://www.wavecom.com.au/04_product_documents/1102/User%20Manual_TnT%20RCD%20Manual_Ver_2.00.pdf",
            "datasheet" : "https://www.wavecom.com.au/04_product_documents/1102/Brochure_TnT%20RCD_Ver_2.20.pdf"
        },
        {   
            "id": 2,
            "link": "TnT-Titan-20A",
            "name": "TnT Titan 20A",
            "productcode": "RENT-TNT-TITAN-20A",
            "category": "PAT Testers",
            "descriptionS" : "Portable Appliance Tester",
            "descriptionL" : "The TnT Titan 20A is the latest generation of Appliance Tester from Wavecom. Offering an easy to use Portable Appliance Testing system that integrates seamlessly with the new WinPATS App via Bluetooth, the TnT Titan 20A is the cutting edge in appliance testing technology.",
            "imageurl" : "tnttitan20a.png",
            "dailyprice": "120",
            "weeklyprice": "400",
            "fortnightlyprice":"640",
            "monthlyprice":"960",
            "rrp":"1798",
            "wavecomlink":"https://www.wavecom.com.au/product_view.php?id_product=1321",
            "features" : [
                "Fully AS/NZS 3760:2022 compliant",
                "Class I, Class II, RCD, Leakage, Extension Lead tests",
                "Android 4G-Ready Tablet",
                "Bluetooth Connectivity - Control Your TnT Titan via the new WinPATS Pro App. Conduct Tests, Save Results To The Cloud, Create Reports & Run Your Test & Tag Operations From One Place",
                "High power Lithium Ion Battery - Conduct over 3000 sets of Tests on a single charge",
                "Built In Isolation Transformer circuitry for portable RCD Testing",
                "20 amp load current capacity - test 10A & 20A appliances",
                "Current calibration certification to Australian standards",
                "Australian made & designed"
            ],
            "usermanual" : "https://www.wavecom.com.au/04_product_documents/1321/User%20Manual_User%20Manual%20-%20TnT%20Titan_Ver_2.00.pdf",
            "datasheet" : "https://www.wavecom.com.au/04_product_documents/1321/Brochure_TnT%20Titan%20Series_Ver_3.20.pdf"
        },        
        {   
            "id": 3,
            "link": "TnP-500",
            "name": "TnP 500",
            "productcode": "RENT-TNP-500",
            "category": "PAT Testers",
            "descriptionS" : "Portable Appliance Test & Print Kit",
            "descriptionL" : "The TnP-500 is a fully integrated portable appliance tester, offering an all in one testing, recording and printing solution. Offering a range of AS/NZS:3760 tests, the TnP-500 is the best test and tag machine available.",
            "imageurl" : "tnp500.png",
            "dailyprice": "150",
            "weeklyprice": "500",
            "fortnightlyprice":"800",
            "monthlyprice":"1200",
            "rrp":"3098",
            "wavecomlink":"https://www.wavecom.com.au/product_view.php?id_product=26",
            "features" : [
                "Fully AS/NZS 3760:2022 compliant",
                "Class I, Class II, RCD, Leakage, Extension Lead tests",
                "Fully integrated appliance testing & tag printing system",
                "Simplified one button test procedures & easy to read results",
                "Thermal transfer tag printer for high quality, long lasting tags",
                "Tags and printing ribbon included, with optional UV Resistant Tags available",
                "Barcode scanner for faster re-testing",
                "10 amp load current capacity - test 10A appliances",
                "Current calibration certification to Australian standards",
                "Australian made & designed"
            ],
            "usermanual" : "https://www.wavecom.com.au/04_product_documents/26/User%20Manual_TnP%20500_Ver_2.0.pdf",
            "datasheet" : "https://www.wavecom.com.au/04_product_documents/26/Brochure_TnP-500_Ver_2.40.pdf"
        },
        {   
            "id": 4,
            "link": "TnP-Prime-20A",
            "name": "TnP Prime 20A",
            "productcode": "RENT-TNP-PRIME-20A",
            "category": "PAT Testers",
            "descriptionS" : "Portable Appliance Test & Print Kit",
            "descriptionL" : "The TnP Prime 20A is the latest generation of Appliance Tester from Wavecom. Offering a fully integrated testing, tag printing and tag scanning system, the TnP Prime 20A is the cutting edge in appliance testing technology. Featuring Bluetooth connectivity, a 16GB 4G Tablet and the new WinPATS App, the TnP Prime 20A will make testing quicker and easier than ever before.",
            "imageurl" : "tnpprime20a.png",
            "dailyprice": "180",
            "weeklyprice": "600",
            "fortnightlyprice":"960",
            "monthlyprice":"1440",
            "rrp":"4888",
            "wavecomlink":"https://www.wavecom.com.au/product_view.php?id_product=1323",
            "features" : [
                "Fully AS/NZS 3760:2022 compliant",
                "Class I, Class II, RCD, Leakage, Extension Lead tests",
                "Fully integrated appliance testing & tag printing system",
                "Android 4G-Ready Tablet",
                "Bluetooth Connectivity - Control Your TnP Prime via the new WinPATS Pro App. Conduct Tests, Save Results To The Cloud, Create Reports & Run Your Test & Tag Operations From One Place",
                "High power Lithium Ion Battery - Conduct over 3000 sets of Tests on a single charge",
                "Built In Isolation Transformer circuitry for portable RCD Testing",
                "20 amp load current capacity - test 10A & 20A appliances",
                "Heavy Duty Trolley Case (IP67 Rated, Shockproof)",
                "Current calibration certification to Australian standards",
                "Australian made & designed"
            ],
            "usermanual" : "https://www.wavecom.com.au/04_product_documents/1323/User%20Manual_User%20Manual%20-%20TnP%20Prime_Ver_2.00.pdf",
            "datasheet" : "https://www.wavecom.com.au/04_product_documents/1323/Brochure_TnP%20Prime_Ver_2.00.pdf"
        },
        {   
            "id": 5,
            "link": "TnP-3PLM-20A",
            "name": "TnP 3PLM 20A",
            "productcode": "RENT-TNP-3PLM-20A",
            "category": "PAT Testers",
            "descriptionS" : "3 Phase Portable Appliance Test & Print Kit",
            "descriptionL" : "The TnP 3PLM is the latest generation of 3 Phase Appliance Tester from Wavecom, and is Australia's premier 3 Phase PAT testing solution. The TnP 3PLM series offers up to 25A Earth Bond testing, up to 1000V Insulation testing, as well as a range of other AS/NZS:3760:2022 compliant tests. Featuring an easy to use appliance testing system that integrates seamlessly with the new WinPATS App via Bluetooth, the TnP 3PLM is the cutting edge in appliance testing technology.",
            "imageurl" : "tnp3plm.png",
            "dailyprice": "375",
            "weeklyprice": "1250",
            "fortnightlyprice":"2000",
            "monthlyprice":"3000",
            "rrp":"7498",
            "wavecomlink":"https://www.wavecom.com.au/product_view.php?id_product=1326",
            "features" : [
                "Fully AS/NZS 3760:2022 compliant",
                "Tests both single and three phase appliances",
                "Class I, Class II, RCD, Leakage, Extension Lead tests",
                "25A Earth Bond Test & 1000V Insulation Test",
                "Fully integrated appliance testing & tag printing system",
                "Android 4G-Ready Tablet",
                "Bluetooth Connectivity - Control Your TnP Prime via the new WinPATS Pro App. Conduct Tests, Save Results To The Cloud, Create Reports & Run Your Test & Tag Operations From One Place",
                "High power Lithium Ion Battery - Conduct over 3000 sets of Tests on a single charge",
                "Built In Isolation Transformer circuitry for portable RCD Testing",
                "20 amp load current capacity - test 10A & 20A single & three phase appliances",
                "Heavy Duty Trolley Case (IP67 Rated, Shockproof)",
                "Current calibration certification to Australian standards",
                "Australian made & designed"
            ],
            "usermanual" : "https://www.wavecom.com.au/04_product_documents/1326/User%20Manual_User%20Manual%20-%20TnP%203PLM%2020A%20v2.0_Ver_2.00.pdf",
            "datasheet" : "https://www.wavecom.com.au/04_product_documents/1326/Brochure_3PL%20Series_Ver_2.20.pdf"
        },
        {   
            "id": 6,
            "link": "TnP-3PLM-50A",
            "name": "TnP 3PLM 50A",
            "productcode": "RENT-TNP-3PLM-50A",
            "category": "PAT Testers",
            "descriptionS" : "3 Phase Portable Appliance Test & Print Kit",
            "descriptionL" : "The TnP 3PLM is the latest generation of 3 Phase Appliance Tester from Wavecom, and is Australia's premier 3 Phase PAT testing solution. The TnP 3PLM series offers up to 25A Earth Bond testing, up to 1000V Insulation testing, as well as a range of other AS/NZS:3760:2022 compliant tests. Featuring an easy to use appliance testing system that integrates seamlessly with the new WinPATS App via Bluetooth, the TnP 3PLM is the cutting edge in appliance testing technology.",
            "imageurl" : "tnp3plm50a.png",
            "dailyprice": "500",
            "weeklyprice": "1500",
            "fortnightlyprice":"2500",
            "monthlyprice":"3500",
            "rrp":"13888",
            "wavecomlink":"https://www.wavecom.com.au/product_view.php?id_product=1328",
            "features" : [
                "Fully AS/NZS 3760:2022 compliant",
                "Tests both single and three phase appliances",
                "Class I, Class II, RCD, Leakage, Extension Lead tests",
                "25A Earth Bond Test & 1000V Insulation Test",
                "Fully integrated appliance testing & tag printing system",
                "Android 4G-Ready Tablet",
                "Bluetooth Connectivity - Control Your TnP Prime via the new WinPATS Pro App. Conduct Tests, Save Results To The Cloud, Create Reports & Run Your Test & Tag Operations From One Place",
                "High power Lithium Ion Battery - Conduct over 3000 sets of Tests on a single charge",
                "Built In Isolation Transformer circuitry for portable RCD Testing",
                "50 amp load current capacity - test all single & three phase appliances up to 50A",
                "Heavy Duty Trolley Case (IP67 Rated, Shockproof)",
                "Current calibration certification to Australian standards",
                "Australian made & designed"
            ],
            "usermanual" : "https://www.wavecom.com.au/04_product_documents/1328/Brochure_User%20Manual%20-%20TnP%203PLM_Ver_2.00.pdf",
            "datasheet" : "https://www.wavecom.com.au/04_product_documents/1328/Brochure_3PL%20Series_Ver_2.20.pdf"
        }
]
