export default [
        {   
            "id": 1,
            "link": "TnT-RCD-20A",
            "name": "TnT RCD 20A",
            "productcode": "RENT-TNT-RCDX",
            "category": "PAT Testers",
            "descriptionS" : "Portable Appliance Tester",
            "descriptionM": "The TnT RCD is the most affordable battery powered Appliance Tester from Wavecom. Offering an easy to use Portable Appliance Testing system and a long lasting battery, the TnT RCD is the cutting edge in appliance testing technology. ",
            "descriptionL" : "The TnT RCD 20A is our most affordable battery powered offering from our latest generation of appliance testers. Offering a wide range of tests, a long lasting Lithium Ion Battery and an integrated Isolation Transformer for RCD Testing, the TnT RCD 20A offers amazing value. With our renowned one button testing and easy to read results screen, the TnT RCD 20A will make your PAT testing a breeze.",
            "imageurl" : "https://www.wavecom.com.au/02_media/splashpages/tntrcd/tntrcd20a.png",
            "dailyprice": "111",
            "weeklyprice": "222",
            "fortnightlyprice":"333",
            "monthlyprice":"444",
            "rrp":"555",
            "wavecomlink":"www.wavecom.com.au/tbc",
            "features" : [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "usermanual" : "https://www.wavecom.com.au/04_product_documents/1102/User%20Manual_TnT%20RCD%20Manual_Ver_2.00.pdf",
            "datasheet" : "tbc"
        },
        {   
            "id": 2,
            "link": "TnT-Titan-20A",
            "name": "TnT Titan 20A",
            "productcode": "RENT-TNT-TITAN-20A",
            "category": "PAT Testers",
            "descriptionS" : "Portable Appliance Tester",
            "descriptionM": "tbc",
            "descriptionL" : "tbc",
            "imageurl" : "https://www.wavecom.com.au/02_media/splashpages/tnttitan/tnttitan20a.png",
            "dailyprice": "111",
            "weeklyprice": "222",
            "fortnightlyprice":"333",
            "monthlyprice":"444",
            "rrp":"555",
            "wavecomlink":"www.wavecom.com.au/tbc",
            "features" : [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "usermanual" : "tbc",
            "datasheet" : "tbc"
        },        
        {   
            "id": 3,
            "link": "TnP-500",
            "name": "TnP 500",
            "productcode": "RENT-TNP-500",
            "category": "PAT Testers",
            "descriptionS" : "Portable Appliance Test & Print Kit",
            "descriptionM": "tbc",
            "descriptionL" : "tbc",
            "imageurl" : "https://www.wavecom.com.au/03_product_images/26/WCM-TNP-500.jpg",
            "dailyprice": "111",
            "weeklyprice": "222",
            "fortnightlyprice":"333",
            "monthlyprice":"444",
            "rrp":"555",
            "wavecomlink":"www.wavecom.com.au/tbc",
            "features" : [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "usermanual" : "tbc",
            "datasheet" : "tbc"
        },
        {   
            "id": 4,
            "link": "TnP-Prime-20A",
            "name": "TnP Prime 20A",
            "productcode": "RENT-TNP-PRIME-20A",
            "category": "PAT Testers",
            "descriptionS" : "Portable Appliance Test & Print Kit",
            "descriptionM": "tbc",
            "descriptionL" : "tbc",
            "imageurl" : "https://www.wavecom.com.au/02_media/splashpages/tnpprime/tnpprime20a.png",
            "dailyprice": "111",
            "weeklyprice": "222",
            "fortnightlyprice":"333",
            "monthlyprice":"444",
            "rrp":"555",
            "wavecomlink":"www.wavecom.com.au/tbc",
            "features" : [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "usermanual" : "tbc",
            "datasheet" : "tbc"
        },
        {   
            "id": 5,
            "link": "TnP-3PLM-20A",
            "name": "TnP 3PLM 20A",
            "productcode": "RENT-TNP-3PLM-20A",
            "category": "PAT Testers",
            "descriptionS" : "3 Phase Portable Appliance Test & Print Kit",
            "descriptionM": "tbc",
            "descriptionL" : "tbc",
            "imageurl" : "https://wavecom.com.au/02_media/splashpages/3pl/tnp3plm.png",
            "dailyprice": "111",
            "weeklyprice": "222",
            "fortnightlyprice":"333",
            "monthlyprice":"444",
            "rrp":"555",
            "wavecomlink":"www.wavecom.com.au/tbc",
            "features" : [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "usermanual" : "tbc",
            "datasheet" : "tbc"
        },
        {   
            "id": 6,
            "link": "TnP-3PLM-50A",
            "name": "TnP 3PLM 50A",
            "productcode": "RENT-TNP-3PLM-50A",
            "category": "PAT Testers",
            "descriptionS" : "3 Phase Portable Appliance Test & Print Kit",
            "descriptionM": "tbc",
            "descriptionL" : "tbc",
            "imageurl" : "https://wavecom.com.au/02_media/splashpages/3pl/tnp3plm50a.png",
            "dailyprice": "111",
            "weeklyprice": "222",
            "fortnightlyprice":"333",
            "monthlyprice":"444",
            "rrp":"555",
            "wavecomlink":"www.wavecom.com.au/tbc",
            "features" : [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "usermanual" : "tbc",
            "datasheet" : "tbc"
        }
]
